

remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/primer@v0.6.0

title: Jacob Everist
description: Information and research projects

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# theme: jekyll-theme-minimal
